INSTRUMENT_TYPE_LABELS = {
    "share": "Акции",
    "bond": "Облигации",
    "etf": "Фонды",
    "currency": "Валюта",
    "futures": "Фьючерсы",
    "option": "Опционы",
    "sp": "Структурные ноты",
    "commodity": "Товары",
}

ALLOCATION_LABELS = {
    "shares": "Акции",
    "bonds": "Облигации",
    "etf": "Фонды",
    "currencies": "Валюта",
    "futures": "Фьючерсы",
    "options": "Опционы",
    "sp": "Структурные ноты",
    "dfa": "Смарт-активы",
}

OPERATION_STATE_LABELS = {
    "OPERATION_STATE_UNSPECIFIED": "Не определён",
    "OPERATION_STATE_EXECUTED": "Исполнена",
    "OPERATION_STATE_CANCELED": "Отменена",
    "OPERATION_STATE_PROGRESS": "В процессе",
}

OPERATION_TYPE_LABELS = {
    "OPERATION_TYPE_UNSPECIFIED": "Не определён",
    "OPERATION_TYPE_INPUT": "Пополнение",
    "OPERATION_TYPE_BOND_TAX": "НДФЛ по купонам",
    "OPERATION_TYPE_OUTPUT_SECURITIES": "Вывод ЦБ",
    "OPERATION_TYPE_OVERNIGHT": "Овернайт РЕПО",
    "OPERATION_TYPE_TAX": "Налог",
    "OPERATION_TYPE_BOND_REPAYMENT_FULL": "Погашение облигаций",
    "OPERATION_TYPE_SELL_CARD": "Продажа с карты",
    "OPERATION_TYPE_DIVIDEND_TAX": "Налог на дивиденды",
    "OPERATION_TYPE_OUTPUT": "Вывод средств",
    "OPERATION_TYPE_BOND_REPAYMENT": "Частичное погашение",
    "OPERATION_TYPE_TAX_CORRECTION": "Корректировка налога",
    "OPERATION_TYPE_SERVICE_FEE": "Комиссия за обслуживание",
    "OPERATION_TYPE_BENEFIT_TAX": "Налог за матвыгоду",
    "OPERATION_TYPE_MARGIN_FEE": "Комиссия за маржу",
    "OPERATION_TYPE_BUY": "Покупка",
    "OPERATION_TYPE_BUY_CARD": "Покупка с карты",
    "OPERATION_TYPE_INPUT_SECURITIES": "Ввод ЦБ",
    "OPERATION_TYPE_SELL_MARGIN": "Продажа Margin-call",
    "OPERATION_TYPE_BROKER_FEE": "Комиссия брокера",
    "OPERATION_TYPE_BUY_MARGIN": "Покупка Margin-call",
    "OPERATION_TYPE_DIVIDEND": "Дивиденды",
    "OPERATION_TYPE_SELL": "Продажа",
    "OPERATION_TYPE_COUPON": "Купон",
    "OPERATION_TYPE_SUCCESS_FEE": "SuccessFee",
    "OPERATION_TYPE_DIVIDEND_TRANSFER": "Передача дивидендов",
    "OPERATION_TYPE_ACCRUING_VARMARGIN": "Зачисление вар. маржи",
    "OPERATION_TYPE_WRITING_OFF_VARMARGIN": "Списание вар. маржи",
    "OPERATION_TYPE_DELIVERY_BUY": "Поставка (покупка)",
    "OPERATION_TYPE_DELIVERY_SELL": "Поставка (продажа)",
    "OPERATION_TYPE_TRACK_MFEE": "Комиссия автоследования",
    "OPERATION_TYPE_TRACK_PFEE": "Комиссия за результат",
    "OPERATION_TYPE_TAX_PROGRESSIVE": "Налог 15%",
    "OPERATION_TYPE_BOND_TAX_PROGRESSIVE": "НДФЛ по купонам 15%",
    "OPERATION_TYPE_DIVIDEND_TAX_PROGRESSIVE": "Налог на дивиденды 15%",
    "OPERATION_TYPE_BENEFIT_TAX_PROGRESSIVE": "Налог за матвыгоду 15%",
    "OPERATION_TYPE_TAX_CORRECTION_PROGRESSIVE": "Корректировка налога 15%",
    "OPERATION_TYPE_TAX_REPO_PROGRESSIVE": "Налог РЕПО 15%",
    "OPERATION_TYPE_TAX_REPO": "Налог РЕПО",
    "OPERATION_TYPE_TAX_REPO_HOLD": "Удержание налога РЕПО",
    "OPERATION_TYPE_TAX_REPO_REFUND": "Возврат налога РЕПО",
    "OPERATION_TYPE_TAX_REPO_HOLD_PROGRESSIVE": "Удержание налога РЕПО 15%",
    "OPERATION_TYPE_TAX_REPO_REFUND_PROGRESSIVE": "Возврат налога РЕПО 15%",
    "OPERATION_TYPE_DIV_EXT": "Дивиденды на карту",
    "OPERATION_TYPE_TAX_CORRECTION_COUPON": "Корректировка налога по купонам",
    "OPERATION_TYPE_CASH_FEE": "Комиссия за валютный остаток",
    "OPERATION_TYPE_OUT_FEE": "Комиссия за вывод валюты",
    "OPERATION_TYPE_OUT_STAMP_DUTY": "Гербовый сбор",
    "OPERATION_TYPE_OUTPUT_SWIFT": "SWIFT-вывод",
    "OPERATION_TYPE_INPUT_SWIFT": "SWIFT-пополнение",
    "OPERATION_TYPE_OUTPUT_ACQUIRING": "Перевод на карту",
    "OPERATION_TYPE_INPUT_ACQUIRING": "Перевод с карты",
    "OPERATION_TYPE_OUTPUT_PENALTY": "Комиссия за вывод",
    "OPERATION_TYPE_ADVICE_FEE": "Оплата сервиса Советов",
    "OPERATION_TYPE_TRANS_IIS_BS": "Перевод ЦБ с ИИС",
    "OPERATION_TYPE_TRANS_BS_BS": "Перевод ЦБ между счетами",
    "OPERATION_TYPE_OUT_MULTI": "Вывод средств",
    "OPERATION_TYPE_INP_MULTI": "Пополнение",
    "OPERATION_TYPE_OVER_PLACEMENT": "Размещение овернайта",
    "OPERATION_TYPE_OVER_COM": "Комиссия овернайта",
    "OPERATION_TYPE_OVER_INCOME": "Доход овернайта",
    "OPERATION_TYPE_OPTION_EXPIRATION": "Экспирация опциона",
    "OPERATION_TYPE_FUTURE_EXPIRATION": "Экспирация фьючерса",
    "OPERATION_TYPE_OTHER_FEE": "Прочая комиссия",
    "OPERATION_TYPE_OTHER": "Прочее",
    "OPERATION_TYPE_DFA_REDEMPTION": "Погашение ЦФА",
}
